name: smoke
channels:
  - conda-forge
  - defaults

dependencies:

  - python=3.11


  - numpy
  - pandas
  - matplotlib
  - seaborn


  - ipykernel
  - notebook


  - pre-commit
  - flake8
  - mypy
  - black


  - pip
  - pip:
      - pathlib
